image: 
  file: .gitpod.Dockerfile

tasks:
  - name: Project build (cache) and run instructions
    init: cargo build --release
    command: |
      # Await for meilisearch to be fully up
      until curl --silent --show-error --fail http://localhost:7700/health; do sleep 0.5; done

      # Start the bot or share info
      if test -v DISCORD_BOT_TOKEN && test -v DISCORD_APP_ID; then
        echo  bot_token=${DISCORD_BOT_TOKEN} \
              app_id=${DISCORD_APP_ID} \
              $(test -v GITHUB_TOKEN && echo github_token=${GITHUB_TOKEN} ||:) \
              meilisearch_api_key=${MEILISEARCH_API_KEY} \
        | cargo run
      else
        printf '%s\n'
          ">>> You can now run something as below to start the bot:"\
          "" \
          $'\033[1;33m'"  echo bot_token=YOUR_TOKEN_HERE app_id=YOUR_APPID_HERE meilisearch_api_key=${MEILISEARCH_API_KEY} | cargo run"$'\033[0m'
      fi

  - name: Meilisearch
    command: |
      meilisearch --no-analytics --master-key "${MEILISEARCH_API_KEY}" --env development --http-addr 0.0.0.0:7700 --db-path ./data.ms

vscode:
  extensions:
    - matklad.rust-analyzer

github:
  prebuilds:
    # enable for the default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: false
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    # DANGER: do not enable!!
    pullRequestsFromForks: false
    # add a check to pull requests (defaults to true)
    addCheck: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: true
    # add a "Review in Gitpod" button to the pull request's description (defaults to false)
    addBadge: true
